# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matteius/cloner-2.5.43-ubuntu_thingino_t31/thingino-cloner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matteius/cloner-2.5.43-ubuntu_thingino_t31/thingino-cloner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteius/cloner-2.5.43-ubuntu_thingino_t31/thingino-cloner/CMakeFiles /home/matteius/cloner-2.5.43-ubuntu_thingino_t31/thingino-cloner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteius/cloner-2.5.43-ubuntu_thingino_t31/thingino-cloner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named thingino-cloner

# Build rule for target.
thingino-cloner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thingino-cloner
.PHONY : thingino-cloner

# fast build rule for target.
thingino-cloner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/build
.PHONY : thingino-cloner/fast

#=============================================================================
# Target rules for targets named test_ddr_generator

# Build rule for target.
test_ddr_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddr_generator
.PHONY : test_ddr_generator

# fast build rule for target.
test_ddr_generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/build
.PHONY : test_ddr_generator/fast

#=============================================================================
# Target rules for targets named test_ddr_multiplechip

# Build rule for target.
test_ddr_multiplechip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddr_multiplechip
.PHONY : test_ddr_multiplechip

# fast build rule for target.
test_ddr_multiplechip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/build
.PHONY : test_ddr_multiplechip/fast

#=============================================================================
# Target rules for targets named test_ddr_reference_analysis

# Build rule for target.
test_ddr_reference_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddr_reference_analysis
.PHONY : test_ddr_reference_analysis

# fast build rule for target.
test_ddr_reference_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_reference_analysis.dir/build.make CMakeFiles/test_ddr_reference_analysis.dir/build
.PHONY : test_ddr_reference_analysis/fast

#=============================================================================
# Target rules for targets named test_ddr_mapping_analysis

# Build rule for target.
test_ddr_mapping_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddr_mapping_analysis
.PHONY : test_ddr_mapping_analysis

# fast build rule for target.
test_ddr_mapping_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/build
.PHONY : test_ddr_mapping_analysis/fast

#=============================================================================
# Target rules for targets named test_txx_mapping_analysis

# Build rule for target.
test_txx_mapping_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_txx_mapping_analysis
.PHONY : test_txx_mapping_analysis

# fast build rule for target.
test_txx_mapping_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_txx_mapping_analysis.dir/build.make CMakeFiles/test_txx_mapping_analysis.dir/build
.PHONY : test_txx_mapping_analysis/fast

#=============================================================================
# Target rules for targets named test_ddrc_analysis

# Build rule for target.
test_ddrc_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddrc_analysis
.PHONY : test_ddrc_analysis

# fast build rule for target.
test_ddrc_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddrc_analysis.dir/build.make CMakeFiles/test_ddrc_analysis.dir/build
.PHONY : test_ddrc_analysis/fast

#=============================================================================
# Target rules for targets named test_binary_builder

# Build rule for target.
test_binary_builder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_binary_builder
.PHONY : test_binary_builder

# fast build rule for target.
test_binary_builder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/build
.PHONY : test_binary_builder/fast

#=============================================================================
# Target rules for targets named test_ddr_integration

# Build rule for target.
test_ddr_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ddr_integration
.PHONY : test_ddr_integration

# fast build rule for target.
test_ddr_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/build
.PHONY : test_ddr_integration/fast

#=============================================================================
# Target rules for targets named test_config_database

# Build rule for target.
test_config_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config_database
.PHONY : test_config_database

# fast build rule for target.
test_config_database/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/build
.PHONY : test_config_database/fast

#=============================================================================
# Target rules for targets named test_firmware_database

# Build rule for target.
test_firmware_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_firmware_database
.PHONY : test_firmware_database

# fast build rule for target.
test_firmware_database/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/build
.PHONY : test_firmware_database/fast

src/bootstrap.o: src/bootstrap.c.o
.PHONY : src/bootstrap.o

# target to build an object file
src/bootstrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/bootstrap.c.o
.PHONY : src/bootstrap.c.o

src/bootstrap.i: src/bootstrap.c.i
.PHONY : src/bootstrap.i

# target to preprocess a source file
src/bootstrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/bootstrap.c.i
.PHONY : src/bootstrap.c.i

src/bootstrap.s: src/bootstrap.c.s
.PHONY : src/bootstrap.s

# target to generate assembly for a file
src/bootstrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/bootstrap.c.s
.PHONY : src/bootstrap.c.s

src/ddr/ddr_binary_builder.o: src/ddr/ddr_binary_builder.c.o
.PHONY : src/ddr/ddr_binary_builder.o

# target to build an object file
src/ddr/ddr_binary_builder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_binary_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_binary_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_binary_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_binary_builder.c.o
.PHONY : src/ddr/ddr_binary_builder.c.o

src/ddr/ddr_binary_builder.i: src/ddr/ddr_binary_builder.c.i
.PHONY : src/ddr/ddr_binary_builder.i

# target to preprocess a source file
src/ddr/ddr_binary_builder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_binary_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_binary_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_binary_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_binary_builder.c.i
.PHONY : src/ddr/ddr_binary_builder.c.i

src/ddr/ddr_binary_builder.s: src/ddr/ddr_binary_builder.c.s
.PHONY : src/ddr/ddr_binary_builder.s

# target to generate assembly for a file
src/ddr/ddr_binary_builder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_binary_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_binary_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_binary_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_binary_builder.c.s
.PHONY : src/ddr/ddr_binary_builder.c.s

src/ddr/ddr_config_database.o: src/ddr/ddr_config_database.c.o
.PHONY : src/ddr/ddr_config_database.o

# target to build an object file
src/ddr/ddr_config_database.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_config_database.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_config_database.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_config_database.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_config_database.c.o
.PHONY : src/ddr/ddr_config_database.c.o

src/ddr/ddr_config_database.i: src/ddr/ddr_config_database.c.i
.PHONY : src/ddr/ddr_config_database.i

# target to preprocess a source file
src/ddr/ddr_config_database.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_config_database.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_config_database.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_config_database.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_config_database.c.i
.PHONY : src/ddr/ddr_config_database.c.i

src/ddr/ddr_config_database.s: src/ddr/ddr_config_database.c.s
.PHONY : src/ddr/ddr_config_database.s

# target to generate assembly for a file
src/ddr/ddr_config_database.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_config_database.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/ddr/ddr_config_database.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/ddr/ddr_config_database.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/ddr/ddr_config_database.c.s
.PHONY : src/ddr/ddr_config_database.c.s

src/ddr/ddr_controller.o: src/ddr/ddr_controller.c.o
.PHONY : src/ddr/ddr_controller.o

# target to build an object file
src/ddr/ddr_controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_controller.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_controller.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_controller.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_controller.c.o
.PHONY : src/ddr/ddr_controller.c.o

src/ddr/ddr_controller.i: src/ddr/ddr_controller.c.i
.PHONY : src/ddr/ddr_controller.i

# target to preprocess a source file
src/ddr/ddr_controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_controller.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_controller.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_controller.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_controller.c.i
.PHONY : src/ddr/ddr_controller.c.i

src/ddr/ddr_controller.s: src/ddr/ddr_controller.c.s
.PHONY : src/ddr/ddr_controller.s

# target to generate assembly for a file
src/ddr/ddr_controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_controller.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_controller.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_controller.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_controller.c.s
.PHONY : src/ddr/ddr_controller.c.s

src/ddr/ddr_ctrl_txx.o: src/ddr/ddr_ctrl_txx.c.o
.PHONY : src/ddr/ddr_ctrl_txx.o

# target to build an object file
src/ddr/ddr_ctrl_txx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_ctrl_txx.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_ctrl_txx.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_ctrl_txx.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_ctrl_txx.c.o
.PHONY : src/ddr/ddr_ctrl_txx.c.o

src/ddr/ddr_ctrl_txx.i: src/ddr/ddr_ctrl_txx.c.i
.PHONY : src/ddr/ddr_ctrl_txx.i

# target to preprocess a source file
src/ddr/ddr_ctrl_txx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_ctrl_txx.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_ctrl_txx.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_ctrl_txx.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_ctrl_txx.c.i
.PHONY : src/ddr/ddr_ctrl_txx.c.i

src/ddr/ddr_ctrl_txx.s: src/ddr/ddr_ctrl_txx.c.s
.PHONY : src/ddr/ddr_ctrl_txx.s

# target to generate assembly for a file
src/ddr/ddr_ctrl_txx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_ctrl_txx.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_ctrl_txx.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_ctrl_txx.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_ctrl_txx.c.s
.PHONY : src/ddr/ddr_ctrl_txx.c.s

src/ddr/ddr_generator.o: src/ddr/ddr_generator.c.o
.PHONY : src/ddr/ddr_generator.o

# target to build an object file
src/ddr/ddr_generator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_generator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_generator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_generator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_generator.c.o
.PHONY : src/ddr/ddr_generator.c.o

src/ddr/ddr_generator.i: src/ddr/ddr_generator.c.i
.PHONY : src/ddr/ddr_generator.i

# target to preprocess a source file
src/ddr/ddr_generator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_generator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_generator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_generator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_generator.c.i
.PHONY : src/ddr/ddr_generator.c.i

src/ddr/ddr_generator.s: src/ddr/ddr_generator.c.s
.PHONY : src/ddr/ddr_generator.s

# target to generate assembly for a file
src/ddr/ddr_generator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_generator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_generator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_generator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_generator.c.s
.PHONY : src/ddr/ddr_generator.c.s

src/ddr/ddr_param_builder.o: src/ddr/ddr_param_builder.c.o
.PHONY : src/ddr/ddr_param_builder.o

# target to build an object file
src/ddr/ddr_param_builder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_param_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_param_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_param_builder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_param_builder.c.o
.PHONY : src/ddr/ddr_param_builder.c.o

src/ddr/ddr_param_builder.i: src/ddr/ddr_param_builder.c.i
.PHONY : src/ddr/ddr_param_builder.i

# target to preprocess a source file
src/ddr/ddr_param_builder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_param_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_param_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_param_builder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_param_builder.c.i
.PHONY : src/ddr/ddr_param_builder.c.i

src/ddr/ddr_param_builder.s: src/ddr/ddr_param_builder.c.s
.PHONY : src/ddr/ddr_param_builder.s

# target to generate assembly for a file
src/ddr/ddr_param_builder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_param_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_param_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_param_builder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_param_builder.c.s
.PHONY : src/ddr/ddr_param_builder.c.s

src/ddr/ddr_phy.o: src/ddr/ddr_phy.c.o
.PHONY : src/ddr/ddr_phy.o

# target to build an object file
src/ddr/ddr_phy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy.c.o
.PHONY : src/ddr/ddr_phy.c.o

src/ddr/ddr_phy.i: src/ddr/ddr_phy.c.i
.PHONY : src/ddr/ddr_phy.i

# target to preprocess a source file
src/ddr/ddr_phy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy.c.i
.PHONY : src/ddr/ddr_phy.c.i

src/ddr/ddr_phy.s: src/ddr/ddr_phy.c.s
.PHONY : src/ddr/ddr_phy.s

# target to generate assembly for a file
src/ddr/ddr_phy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy.c.s
.PHONY : src/ddr/ddr_phy.c.s

src/ddr/ddr_phy_ddr2.o: src/ddr/ddr_phy_ddr2.c.o
.PHONY : src/ddr/ddr_phy_ddr2.o

# target to build an object file
src/ddr/ddr_phy_ddr2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy_ddr2.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy_ddr2.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy_ddr2.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy_ddr2.c.o
.PHONY : src/ddr/ddr_phy_ddr2.c.o

src/ddr/ddr_phy_ddr2.i: src/ddr/ddr_phy_ddr2.c.i
.PHONY : src/ddr/ddr_phy_ddr2.i

# target to preprocess a source file
src/ddr/ddr_phy_ddr2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy_ddr2.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy_ddr2.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy_ddr2.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy_ddr2.c.i
.PHONY : src/ddr/ddr_phy_ddr2.c.i

src/ddr/ddr_phy_ddr2.s: src/ddr/ddr_phy_ddr2.c.s
.PHONY : src/ddr/ddr_phy_ddr2.s

# target to generate assembly for a file
src/ddr/ddr_phy_ddr2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_phy_ddr2.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_phy_ddr2.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_phy_ddr2.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_phy_ddr2.c.s
.PHONY : src/ddr/ddr_phy_ddr2.c.s

src/ddr/ddr_utils.o: src/ddr/ddr_utils.c.o
.PHONY : src/ddr/ddr_utils.o

# target to build an object file
src/ddr/ddr_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_utils.c.o
.PHONY : src/ddr/ddr_utils.c.o

src/ddr/ddr_utils.i: src/ddr/ddr_utils.c.i
.PHONY : src/ddr/ddr_utils.i

# target to preprocess a source file
src/ddr/ddr_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_utils.c.i
.PHONY : src/ddr/ddr_utils.c.i

src/ddr/ddr_utils.s: src/ddr/ddr_utils.c.s
.PHONY : src/ddr/ddr_utils.s

# target to generate assembly for a file
src/ddr/ddr_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/ddr_utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/ddr/ddr_utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/ddr/ddr_utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/ddr/ddr_utils.c.s
.PHONY : src/ddr/ddr_utils.c.s

src/ddr/parser.o: src/ddr/parser.c.o
.PHONY : src/ddr/parser.o

# target to build an object file
src/ddr/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/parser.c.o
.PHONY : src/ddr/parser.c.o

src/ddr/parser.i: src/ddr/parser.c.i
.PHONY : src/ddr/parser.i

# target to preprocess a source file
src/ddr/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/parser.c.i
.PHONY : src/ddr/parser.c.i

src/ddr/parser.s: src/ddr/parser.c.s
.PHONY : src/ddr/parser.s

# target to generate assembly for a file
src/ddr/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/ddr/parser.c.s
.PHONY : src/ddr/parser.c.s

src/firmware/firmware_a1_n_ne_x.o: src/firmware/firmware_a1_n_ne_x.c.o
.PHONY : src/firmware/firmware_a1_n_ne_x.o

# target to build an object file
src/firmware/firmware_a1_n_ne_x.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_n_ne_x.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_n_ne_x.c.o
.PHONY : src/firmware/firmware_a1_n_ne_x.c.o

src/firmware/firmware_a1_n_ne_x.i: src/firmware/firmware_a1_n_ne_x.c.i
.PHONY : src/firmware/firmware_a1_n_ne_x.i

# target to preprocess a source file
src/firmware/firmware_a1_n_ne_x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_n_ne_x.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_n_ne_x.c.i
.PHONY : src/firmware/firmware_a1_n_ne_x.c.i

src/firmware/firmware_a1_n_ne_x.s: src/firmware/firmware_a1_n_ne_x.c.s
.PHONY : src/firmware/firmware_a1_n_ne_x.s

# target to generate assembly for a file
src/firmware/firmware_a1_n_ne_x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_n_ne_x.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_n_ne_x.c.s
.PHONY : src/firmware/firmware_a1_n_ne_x.c.s

src/firmware/firmware_a1_nt_a.o: src/firmware/firmware_a1_nt_a.c.o
.PHONY : src/firmware/firmware_a1_nt_a.o

# target to build an object file
src/firmware/firmware_a1_nt_a.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_nt_a.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_nt_a.c.o
.PHONY : src/firmware/firmware_a1_nt_a.c.o

src/firmware/firmware_a1_nt_a.i: src/firmware/firmware_a1_nt_a.c.i
.PHONY : src/firmware/firmware_a1_nt_a.i

# target to preprocess a source file
src/firmware/firmware_a1_nt_a.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_nt_a.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_nt_a.c.i
.PHONY : src/firmware/firmware_a1_nt_a.c.i

src/firmware/firmware_a1_nt_a.s: src/firmware/firmware_a1_nt_a.c.s
.PHONY : src/firmware/firmware_a1_nt_a.s

# target to generate assembly for a file
src/firmware/firmware_a1_nt_a.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_a1_nt_a.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_a1_nt_a.c.s
.PHONY : src/firmware/firmware_a1_nt_a.c.s

src/firmware/firmware_database.o: src/firmware/firmware_database.c.o
.PHONY : src/firmware/firmware_database.o

# target to build an object file
src/firmware/firmware_database.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_database.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_database.c.o
.PHONY : src/firmware/firmware_database.c.o

src/firmware/firmware_database.i: src/firmware/firmware_database.c.i
.PHONY : src/firmware/firmware_database.i

# target to preprocess a source file
src/firmware/firmware_database.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_database.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_database.c.i
.PHONY : src/firmware/firmware_database.c.i

src/firmware/firmware_database.s: src/firmware/firmware_database.c.s
.PHONY : src/firmware/firmware_database.s

# target to generate assembly for a file
src/firmware/firmware_database.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_database.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_database.c.s
.PHONY : src/firmware/firmware_database.c.s

src/firmware/firmware_t20.o: src/firmware/firmware_t20.c.o
.PHONY : src/firmware/firmware_t20.o

# target to build an object file
src/firmware/firmware_t20.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t20.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t20.c.o
.PHONY : src/firmware/firmware_t20.c.o

src/firmware/firmware_t20.i: src/firmware/firmware_t20.c.i
.PHONY : src/firmware/firmware_t20.i

# target to preprocess a source file
src/firmware/firmware_t20.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t20.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t20.c.i
.PHONY : src/firmware/firmware_t20.c.i

src/firmware/firmware_t20.s: src/firmware/firmware_t20.c.s
.PHONY : src/firmware/firmware_t20.s

# target to generate assembly for a file
src/firmware/firmware_t20.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t20.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t20.c.s
.PHONY : src/firmware/firmware_t20.c.s

src/firmware/firmware_t21.o: src/firmware/firmware_t21.c.o
.PHONY : src/firmware/firmware_t21.o

# target to build an object file
src/firmware/firmware_t21.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t21.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t21.c.o
.PHONY : src/firmware/firmware_t21.c.o

src/firmware/firmware_t21.i: src/firmware/firmware_t21.c.i
.PHONY : src/firmware/firmware_t21.i

# target to preprocess a source file
src/firmware/firmware_t21.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t21.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t21.c.i
.PHONY : src/firmware/firmware_t21.c.i

src/firmware/firmware_t21.s: src/firmware/firmware_t21.c.s
.PHONY : src/firmware/firmware_t21.s

# target to generate assembly for a file
src/firmware/firmware_t21.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t21.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t21.c.s
.PHONY : src/firmware/firmware_t21.c.s

src/firmware/firmware_t23.o: src/firmware/firmware_t23.c.o
.PHONY : src/firmware/firmware_t23.o

# target to build an object file
src/firmware/firmware_t23.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t23.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t23.c.o
.PHONY : src/firmware/firmware_t23.c.o

src/firmware/firmware_t23.i: src/firmware/firmware_t23.c.i
.PHONY : src/firmware/firmware_t23.i

# target to preprocess a source file
src/firmware/firmware_t23.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t23.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t23.c.i
.PHONY : src/firmware/firmware_t23.c.i

src/firmware/firmware_t23.s: src/firmware/firmware_t23.c.s
.PHONY : src/firmware/firmware_t23.s

# target to generate assembly for a file
src/firmware/firmware_t23.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t23.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t23.c.s
.PHONY : src/firmware/firmware_t23.c.s

src/firmware/firmware_t30.o: src/firmware/firmware_t30.c.o
.PHONY : src/firmware/firmware_t30.o

# target to build an object file
src/firmware/firmware_t30.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30.c.o
.PHONY : src/firmware/firmware_t30.c.o

src/firmware/firmware_t30.i: src/firmware/firmware_t30.c.i
.PHONY : src/firmware/firmware_t30.i

# target to preprocess a source file
src/firmware/firmware_t30.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30.c.i
.PHONY : src/firmware/firmware_t30.c.i

src/firmware/firmware_t30.s: src/firmware/firmware_t30.c.s
.PHONY : src/firmware/firmware_t30.s

# target to generate assembly for a file
src/firmware/firmware_t30.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30.c.s
.PHONY : src/firmware/firmware_t30.c.s

src/firmware/firmware_t30a.o: src/firmware/firmware_t30a.c.o
.PHONY : src/firmware/firmware_t30a.o

# target to build an object file
src/firmware/firmware_t30a.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30a.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30a.c.o
.PHONY : src/firmware/firmware_t30a.c.o

src/firmware/firmware_t30a.i: src/firmware/firmware_t30a.c.i
.PHONY : src/firmware/firmware_t30a.i

# target to preprocess a source file
src/firmware/firmware_t30a.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30a.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30a.c.i
.PHONY : src/firmware/firmware_t30a.c.i

src/firmware/firmware_t30a.s: src/firmware/firmware_t30a.c.s
.PHONY : src/firmware/firmware_t30a.s

# target to generate assembly for a file
src/firmware/firmware_t30a.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30a.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30a.c.s
.PHONY : src/firmware/firmware_t30a.c.s

src/firmware/firmware_t30nl.o: src/firmware/firmware_t30nl.c.o
.PHONY : src/firmware/firmware_t30nl.o

# target to build an object file
src/firmware/firmware_t30nl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30nl.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30nl.c.o
.PHONY : src/firmware/firmware_t30nl.c.o

src/firmware/firmware_t30nl.i: src/firmware/firmware_t30nl.c.i
.PHONY : src/firmware/firmware_t30nl.i

# target to preprocess a source file
src/firmware/firmware_t30nl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30nl.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30nl.c.i
.PHONY : src/firmware/firmware_t30nl.c.i

src/firmware/firmware_t30nl.s: src/firmware/firmware_t30nl.c.s
.PHONY : src/firmware/firmware_t30nl.s

# target to generate assembly for a file
src/firmware/firmware_t30nl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30nl.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30nl.c.s
.PHONY : src/firmware/firmware_t30nl.c.s

src/firmware/firmware_t30x.o: src/firmware/firmware_t30x.c.o
.PHONY : src/firmware/firmware_t30x.o

# target to build an object file
src/firmware/firmware_t30x.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30x.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30x.c.o
.PHONY : src/firmware/firmware_t30x.c.o

src/firmware/firmware_t30x.i: src/firmware/firmware_t30x.c.i
.PHONY : src/firmware/firmware_t30x.i

# target to preprocess a source file
src/firmware/firmware_t30x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30x.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30x.c.i
.PHONY : src/firmware/firmware_t30x.c.i

src/firmware/firmware_t30x.s: src/firmware/firmware_t30x.c.s
.PHONY : src/firmware/firmware_t30x.s

# target to generate assembly for a file
src/firmware/firmware_t30x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t30x.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t30x.c.s
.PHONY : src/firmware/firmware_t30x.c.s

src/firmware/firmware_t31.o: src/firmware/firmware_t31.c.o
.PHONY : src/firmware/firmware_t31.o

# target to build an object file
src/firmware/firmware_t31.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31.c.o
.PHONY : src/firmware/firmware_t31.c.o

src/firmware/firmware_t31.i: src/firmware/firmware_t31.c.i
.PHONY : src/firmware/firmware_t31.i

# target to preprocess a source file
src/firmware/firmware_t31.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31.c.i
.PHONY : src/firmware/firmware_t31.c.i

src/firmware/firmware_t31.s: src/firmware/firmware_t31.c.s
.PHONY : src/firmware/firmware_t31.s

# target to generate assembly for a file
src/firmware/firmware_t31.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31.c.s
.PHONY : src/firmware/firmware_t31.c.s

src/firmware/firmware_t31a.o: src/firmware/firmware_t31a.c.o
.PHONY : src/firmware/firmware_t31a.o

# target to build an object file
src/firmware/firmware_t31a.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31a.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31a.c.o
.PHONY : src/firmware/firmware_t31a.c.o

src/firmware/firmware_t31a.i: src/firmware/firmware_t31a.c.i
.PHONY : src/firmware/firmware_t31a.i

# target to preprocess a source file
src/firmware/firmware_t31a.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31a.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31a.c.i
.PHONY : src/firmware/firmware_t31a.c.i

src/firmware/firmware_t31a.s: src/firmware/firmware_t31a.c.s
.PHONY : src/firmware/firmware_t31a.s

# target to generate assembly for a file
src/firmware/firmware_t31a.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31a.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31a.c.s
.PHONY : src/firmware/firmware_t31a.c.s

src/firmware/firmware_t31nl.o: src/firmware/firmware_t31nl.c.o
.PHONY : src/firmware/firmware_t31nl.o

# target to build an object file
src/firmware/firmware_t31nl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31nl.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31nl.c.o
.PHONY : src/firmware/firmware_t31nl.c.o

src/firmware/firmware_t31nl.i: src/firmware/firmware_t31nl.c.i
.PHONY : src/firmware/firmware_t31nl.i

# target to preprocess a source file
src/firmware/firmware_t31nl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31nl.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31nl.c.i
.PHONY : src/firmware/firmware_t31nl.c.i

src/firmware/firmware_t31nl.s: src/firmware/firmware_t31nl.c.s
.PHONY : src/firmware/firmware_t31nl.s

# target to generate assembly for a file
src/firmware/firmware_t31nl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31nl.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31nl.c.s
.PHONY : src/firmware/firmware_t31nl.c.s

src/firmware/firmware_t31x.o: src/firmware/firmware_t31x.c.o
.PHONY : src/firmware/firmware_t31x.o

# target to build an object file
src/firmware/firmware_t31x.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31x.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31x.c.o
.PHONY : src/firmware/firmware_t31x.c.o

src/firmware/firmware_t31x.i: src/firmware/firmware_t31x.c.i
.PHONY : src/firmware/firmware_t31x.i

# target to preprocess a source file
src/firmware/firmware_t31x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31x.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31x.c.i
.PHONY : src/firmware/firmware_t31x.c.i

src/firmware/firmware_t31x.s: src/firmware/firmware_t31x.c.s
.PHONY : src/firmware/firmware_t31x.s

# target to generate assembly for a file
src/firmware/firmware_t31x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t31x.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t31x.c.s
.PHONY : src/firmware/firmware_t31x.c.s

src/firmware/firmware_t40.o: src/firmware/firmware_t40.c.o
.PHONY : src/firmware/firmware_t40.o

# target to build an object file
src/firmware/firmware_t40.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t40.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t40.c.o
.PHONY : src/firmware/firmware_t40.c.o

src/firmware/firmware_t40.i: src/firmware/firmware_t40.c.i
.PHONY : src/firmware/firmware_t40.i

# target to preprocess a source file
src/firmware/firmware_t40.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t40.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t40.c.i
.PHONY : src/firmware/firmware_t40.c.i

src/firmware/firmware_t40.s: src/firmware/firmware_t40.c.s
.PHONY : src/firmware/firmware_t40.s

# target to generate assembly for a file
src/firmware/firmware_t40.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t40.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t40.c.s
.PHONY : src/firmware/firmware_t40.c.s

src/firmware/firmware_t41.o: src/firmware/firmware_t41.c.o
.PHONY : src/firmware/firmware_t41.o

# target to build an object file
src/firmware/firmware_t41.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t41.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t41.c.o
.PHONY : src/firmware/firmware_t41.c.o

src/firmware/firmware_t41.i: src/firmware/firmware_t41.c.i
.PHONY : src/firmware/firmware_t41.i

# target to preprocess a source file
src/firmware/firmware_t41.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t41.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t41.c.i
.PHONY : src/firmware/firmware_t41.c.i

src/firmware/firmware_t41.s: src/firmware/firmware_t41.c.s
.PHONY : src/firmware/firmware_t41.s

# target to generate assembly for a file
src/firmware/firmware_t41.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/firmware_t41.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/firmware/firmware_t41.c.s
.PHONY : src/firmware/firmware_t41.c.s

src/firmware/flash_descriptor.o: src/firmware/flash_descriptor.c.o
.PHONY : src/firmware/flash_descriptor.o

# target to build an object file
src/firmware/flash_descriptor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/flash_descriptor.c.o
.PHONY : src/firmware/flash_descriptor.c.o

src/firmware/flash_descriptor.i: src/firmware/flash_descriptor.c.i
.PHONY : src/firmware/flash_descriptor.i

# target to preprocess a source file
src/firmware/flash_descriptor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/flash_descriptor.c.i
.PHONY : src/firmware/flash_descriptor.c.i

src/firmware/flash_descriptor.s: src/firmware/flash_descriptor.c.s
.PHONY : src/firmware/flash_descriptor.s

# target to generate assembly for a file
src/firmware/flash_descriptor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/flash_descriptor.c.s
.PHONY : src/firmware/flash_descriptor.c.s

src/firmware/handshake.o: src/firmware/handshake.c.o
.PHONY : src/firmware/handshake.o

# target to build an object file
src/firmware/handshake.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/handshake.c.o
.PHONY : src/firmware/handshake.c.o

src/firmware/handshake.i: src/firmware/handshake.c.i
.PHONY : src/firmware/handshake.i

# target to preprocess a source file
src/firmware/handshake.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/handshake.c.i
.PHONY : src/firmware/handshake.c.i

src/firmware/handshake.s: src/firmware/handshake.c.s
.PHONY : src/firmware/handshake.s

# target to generate assembly for a file
src/firmware/handshake.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/handshake.c.s
.PHONY : src/firmware/handshake.c.s

src/firmware/loader.o: src/firmware/loader.c.o
.PHONY : src/firmware/loader.o

# target to build an object file
src/firmware/loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/loader.c.o
.PHONY : src/firmware/loader.c.o

src/firmware/loader.i: src/firmware/loader.c.i
.PHONY : src/firmware/loader.i

# target to preprocess a source file
src/firmware/loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/loader.c.i
.PHONY : src/firmware/loader.c.i

src/firmware/loader.s: src/firmware/loader.c.s
.PHONY : src/firmware/loader.s

# target to generate assembly for a file
src/firmware/loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/loader.c.s
.PHONY : src/firmware/loader.c.s

src/firmware/reader.o: src/firmware/reader.c.o
.PHONY : src/firmware/reader.o

# target to build an object file
src/firmware/reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/reader.c.o
.PHONY : src/firmware/reader.c.o

src/firmware/reader.i: src/firmware/reader.c.i
.PHONY : src/firmware/reader.i

# target to preprocess a source file
src/firmware/reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/reader.c.i
.PHONY : src/firmware/reader.c.i

src/firmware/reader.s: src/firmware/reader.c.s
.PHONY : src/firmware/reader.s

# target to generate assembly for a file
src/firmware/reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/reader.c.s
.PHONY : src/firmware/reader.c.s

src/firmware/writer.o: src/firmware/writer.c.o
.PHONY : src/firmware/writer.o

# target to build an object file
src/firmware/writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/writer.c.o
.PHONY : src/firmware/writer.c.o

src/firmware/writer.i: src/firmware/writer.c.i
.PHONY : src/firmware/writer.i

# target to preprocess a source file
src/firmware/writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/writer.c.i
.PHONY : src/firmware/writer.c.i

src/firmware/writer.s: src/firmware/writer.c.s
.PHONY : src/firmware/writer.s

# target to generate assembly for a file
src/firmware/writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/firmware/writer.c.s
.PHONY : src/firmware/writer.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/main.c.s
.PHONY : src/main.c.s

src/test_binary_builder.o: src/test_binary_builder.c.o
.PHONY : src/test_binary_builder.o

# target to build an object file
src/test_binary_builder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/test_binary_builder.c.o
.PHONY : src/test_binary_builder.c.o

src/test_binary_builder.i: src/test_binary_builder.c.i
.PHONY : src/test_binary_builder.i

# target to preprocess a source file
src/test_binary_builder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/test_binary_builder.c.i
.PHONY : src/test_binary_builder.c.i

src/test_binary_builder.s: src/test_binary_builder.c.s
.PHONY : src/test_binary_builder.s

# target to generate assembly for a file
src/test_binary_builder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_binary_builder.dir/build.make CMakeFiles/test_binary_builder.dir/src/test_binary_builder.c.s
.PHONY : src/test_binary_builder.c.s

src/test_config_database.o: src/test_config_database.c.o
.PHONY : src/test_config_database.o

# target to build an object file
src/test_config_database.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/test_config_database.c.o
.PHONY : src/test_config_database.c.o

src/test_config_database.i: src/test_config_database.c.i
.PHONY : src/test_config_database.i

# target to preprocess a source file
src/test_config_database.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/test_config_database.c.i
.PHONY : src/test_config_database.c.i

src/test_config_database.s: src/test_config_database.c.s
.PHONY : src/test_config_database.s

# target to generate assembly for a file
src/test_config_database.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config_database.dir/build.make CMakeFiles/test_config_database.dir/src/test_config_database.c.s
.PHONY : src/test_config_database.c.s

src/test_ddr_generator.o: src/test_ddr_generator.c.o
.PHONY : src/test_ddr_generator.o

# target to build an object file
src/test_ddr_generator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/test_ddr_generator.c.o
.PHONY : src/test_ddr_generator.c.o

src/test_ddr_generator.i: src/test_ddr_generator.c.i
.PHONY : src/test_ddr_generator.i

# target to preprocess a source file
src/test_ddr_generator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/test_ddr_generator.c.i
.PHONY : src/test_ddr_generator.c.i

src/test_ddr_generator.s: src/test_ddr_generator.c.s
.PHONY : src/test_ddr_generator.s

# target to generate assembly for a file
src/test_ddr_generator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_generator.dir/build.make CMakeFiles/test_ddr_generator.dir/src/test_ddr_generator.c.s
.PHONY : src/test_ddr_generator.c.s

src/test_ddr_integration.o: src/test_ddr_integration.c.o
.PHONY : src/test_ddr_integration.o

# target to build an object file
src/test_ddr_integration.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/test_ddr_integration.c.o
.PHONY : src/test_ddr_integration.c.o

src/test_ddr_integration.i: src/test_ddr_integration.c.i
.PHONY : src/test_ddr_integration.i

# target to preprocess a source file
src/test_ddr_integration.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/test_ddr_integration.c.i
.PHONY : src/test_ddr_integration.c.i

src/test_ddr_integration.s: src/test_ddr_integration.c.s
.PHONY : src/test_ddr_integration.s

# target to generate assembly for a file
src/test_ddr_integration.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_integration.dir/build.make CMakeFiles/test_ddr_integration.dir/src/test_ddr_integration.c.s
.PHONY : src/test_ddr_integration.c.s

src/test_ddr_mapping_analysis.o: src/test_ddr_mapping_analysis.c.o
.PHONY : src/test_ddr_mapping_analysis.o

# target to build an object file
src/test_ddr_mapping_analysis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/test_ddr_mapping_analysis.c.o
.PHONY : src/test_ddr_mapping_analysis.c.o

src/test_ddr_mapping_analysis.i: src/test_ddr_mapping_analysis.c.i
.PHONY : src/test_ddr_mapping_analysis.i

# target to preprocess a source file
src/test_ddr_mapping_analysis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/test_ddr_mapping_analysis.c.i
.PHONY : src/test_ddr_mapping_analysis.c.i

src/test_ddr_mapping_analysis.s: src/test_ddr_mapping_analysis.c.s
.PHONY : src/test_ddr_mapping_analysis.s

# target to generate assembly for a file
src/test_ddr_mapping_analysis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_mapping_analysis.dir/build.make CMakeFiles/test_ddr_mapping_analysis.dir/src/test_ddr_mapping_analysis.c.s
.PHONY : src/test_ddr_mapping_analysis.c.s

src/test_ddr_multiplechip.o: src/test_ddr_multiplechip.c.o
.PHONY : src/test_ddr_multiplechip.o

# target to build an object file
src/test_ddr_multiplechip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/test_ddr_multiplechip.c.o
.PHONY : src/test_ddr_multiplechip.c.o

src/test_ddr_multiplechip.i: src/test_ddr_multiplechip.c.i
.PHONY : src/test_ddr_multiplechip.i

# target to preprocess a source file
src/test_ddr_multiplechip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/test_ddr_multiplechip.c.i
.PHONY : src/test_ddr_multiplechip.c.i

src/test_ddr_multiplechip.s: src/test_ddr_multiplechip.c.s
.PHONY : src/test_ddr_multiplechip.s

# target to generate assembly for a file
src/test_ddr_multiplechip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_multiplechip.dir/build.make CMakeFiles/test_ddr_multiplechip.dir/src/test_ddr_multiplechip.c.s
.PHONY : src/test_ddr_multiplechip.c.s

src/test_ddr_reference_analysis.o: src/test_ddr_reference_analysis.c.o
.PHONY : src/test_ddr_reference_analysis.o

# target to build an object file
src/test_ddr_reference_analysis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_reference_analysis.dir/build.make CMakeFiles/test_ddr_reference_analysis.dir/src/test_ddr_reference_analysis.c.o
.PHONY : src/test_ddr_reference_analysis.c.o

src/test_ddr_reference_analysis.i: src/test_ddr_reference_analysis.c.i
.PHONY : src/test_ddr_reference_analysis.i

# target to preprocess a source file
src/test_ddr_reference_analysis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_reference_analysis.dir/build.make CMakeFiles/test_ddr_reference_analysis.dir/src/test_ddr_reference_analysis.c.i
.PHONY : src/test_ddr_reference_analysis.c.i

src/test_ddr_reference_analysis.s: src/test_ddr_reference_analysis.c.s
.PHONY : src/test_ddr_reference_analysis.s

# target to generate assembly for a file
src/test_ddr_reference_analysis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddr_reference_analysis.dir/build.make CMakeFiles/test_ddr_reference_analysis.dir/src/test_ddr_reference_analysis.c.s
.PHONY : src/test_ddr_reference_analysis.c.s

src/test_ddrc_analysis.o: src/test_ddrc_analysis.c.o
.PHONY : src/test_ddrc_analysis.o

# target to build an object file
src/test_ddrc_analysis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddrc_analysis.dir/build.make CMakeFiles/test_ddrc_analysis.dir/src/test_ddrc_analysis.c.o
.PHONY : src/test_ddrc_analysis.c.o

src/test_ddrc_analysis.i: src/test_ddrc_analysis.c.i
.PHONY : src/test_ddrc_analysis.i

# target to preprocess a source file
src/test_ddrc_analysis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddrc_analysis.dir/build.make CMakeFiles/test_ddrc_analysis.dir/src/test_ddrc_analysis.c.i
.PHONY : src/test_ddrc_analysis.c.i

src/test_ddrc_analysis.s: src/test_ddrc_analysis.c.s
.PHONY : src/test_ddrc_analysis.s

# target to generate assembly for a file
src/test_ddrc_analysis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ddrc_analysis.dir/build.make CMakeFiles/test_ddrc_analysis.dir/src/test_ddrc_analysis.c.s
.PHONY : src/test_ddrc_analysis.c.s

src/test_firmware_database.o: src/test_firmware_database.c.o
.PHONY : src/test_firmware_database.o

# target to build an object file
src/test_firmware_database.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/test_firmware_database.c.o
.PHONY : src/test_firmware_database.c.o

src/test_firmware_database.i: src/test_firmware_database.c.i
.PHONY : src/test_firmware_database.i

# target to preprocess a source file
src/test_firmware_database.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/test_firmware_database.c.i
.PHONY : src/test_firmware_database.c.i

src/test_firmware_database.s: src/test_firmware_database.c.s
.PHONY : src/test_firmware_database.s

# target to generate assembly for a file
src/test_firmware_database.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_firmware_database.dir/build.make CMakeFiles/test_firmware_database.dir/src/test_firmware_database.c.s
.PHONY : src/test_firmware_database.c.s

src/test_txx_mapping_analysis.o: src/test_txx_mapping_analysis.c.o
.PHONY : src/test_txx_mapping_analysis.o

# target to build an object file
src/test_txx_mapping_analysis.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_txx_mapping_analysis.dir/build.make CMakeFiles/test_txx_mapping_analysis.dir/src/test_txx_mapping_analysis.c.o
.PHONY : src/test_txx_mapping_analysis.c.o

src/test_txx_mapping_analysis.i: src/test_txx_mapping_analysis.c.i
.PHONY : src/test_txx_mapping_analysis.i

# target to preprocess a source file
src/test_txx_mapping_analysis.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_txx_mapping_analysis.dir/build.make CMakeFiles/test_txx_mapping_analysis.dir/src/test_txx_mapping_analysis.c.i
.PHONY : src/test_txx_mapping_analysis.c.i

src/test_txx_mapping_analysis.s: src/test_txx_mapping_analysis.c.s
.PHONY : src/test_txx_mapping_analysis.s

# target to generate assembly for a file
src/test_txx_mapping_analysis.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_txx_mapping_analysis.dir/build.make CMakeFiles/test_txx_mapping_analysis.dir/src/test_txx_mapping_analysis.c.s
.PHONY : src/test_txx_mapping_analysis.c.s

src/usb/device.o: src/usb/device.c.o
.PHONY : src/usb/device.o

# target to build an object file
src/usb/device.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/device.c.o
.PHONY : src/usb/device.c.o

src/usb/device.i: src/usb/device.c.i
.PHONY : src/usb/device.i

# target to preprocess a source file
src/usb/device.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/device.c.i
.PHONY : src/usb/device.c.i

src/usb/device.s: src/usb/device.c.s
.PHONY : src/usb/device.s

# target to generate assembly for a file
src/usb/device.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/device.c.s
.PHONY : src/usb/device.c.s

src/usb/manager.o: src/usb/manager.c.o
.PHONY : src/usb/manager.o

# target to build an object file
src/usb/manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/manager.c.o
.PHONY : src/usb/manager.c.o

src/usb/manager.i: src/usb/manager.c.i
.PHONY : src/usb/manager.i

# target to preprocess a source file
src/usb/manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/manager.c.i
.PHONY : src/usb/manager.c.i

src/usb/manager.s: src/usb/manager.c.s
.PHONY : src/usb/manager.s

# target to generate assembly for a file
src/usb/manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/manager.c.s
.PHONY : src/usb/manager.c.s

src/usb/protocol.o: src/usb/protocol.c.o
.PHONY : src/usb/protocol.o

# target to build an object file
src/usb/protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/protocol.c.o
.PHONY : src/usb/protocol.c.o

src/usb/protocol.i: src/usb/protocol.c.i
.PHONY : src/usb/protocol.i

# target to preprocess a source file
src/usb/protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/protocol.c.i
.PHONY : src/usb/protocol.c.i

src/usb/protocol.s: src/usb/protocol.c.s
.PHONY : src/usb/protocol.s

# target to generate assembly for a file
src/usb/protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/usb/protocol.c.s
.PHONY : src/usb/protocol.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/thingino-cloner.dir/build.make CMakeFiles/thingino-cloner.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test_binary_builder"
	@echo "... test_config_database"
	@echo "... test_ddr_generator"
	@echo "... test_ddr_integration"
	@echo "... test_ddr_mapping_analysis"
	@echo "... test_ddr_multiplechip"
	@echo "... test_ddr_reference_analysis"
	@echo "... test_ddrc_analysis"
	@echo "... test_firmware_database"
	@echo "... test_txx_mapping_analysis"
	@echo "... thingino-cloner"
	@echo "... src/bootstrap.o"
	@echo "... src/bootstrap.i"
	@echo "... src/bootstrap.s"
	@echo "... src/ddr/ddr_binary_builder.o"
	@echo "... src/ddr/ddr_binary_builder.i"
	@echo "... src/ddr/ddr_binary_builder.s"
	@echo "... src/ddr/ddr_config_database.o"
	@echo "... src/ddr/ddr_config_database.i"
	@echo "... src/ddr/ddr_config_database.s"
	@echo "... src/ddr/ddr_controller.o"
	@echo "... src/ddr/ddr_controller.i"
	@echo "... src/ddr/ddr_controller.s"
	@echo "... src/ddr/ddr_ctrl_txx.o"
	@echo "... src/ddr/ddr_ctrl_txx.i"
	@echo "... src/ddr/ddr_ctrl_txx.s"
	@echo "... src/ddr/ddr_generator.o"
	@echo "... src/ddr/ddr_generator.i"
	@echo "... src/ddr/ddr_generator.s"
	@echo "... src/ddr/ddr_param_builder.o"
	@echo "... src/ddr/ddr_param_builder.i"
	@echo "... src/ddr/ddr_param_builder.s"
	@echo "... src/ddr/ddr_phy.o"
	@echo "... src/ddr/ddr_phy.i"
	@echo "... src/ddr/ddr_phy.s"
	@echo "... src/ddr/ddr_phy_ddr2.o"
	@echo "... src/ddr/ddr_phy_ddr2.i"
	@echo "... src/ddr/ddr_phy_ddr2.s"
	@echo "... src/ddr/ddr_utils.o"
	@echo "... src/ddr/ddr_utils.i"
	@echo "... src/ddr/ddr_utils.s"
	@echo "... src/ddr/parser.o"
	@echo "... src/ddr/parser.i"
	@echo "... src/ddr/parser.s"
	@echo "... src/firmware/firmware_a1_n_ne_x.o"
	@echo "... src/firmware/firmware_a1_n_ne_x.i"
	@echo "... src/firmware/firmware_a1_n_ne_x.s"
	@echo "... src/firmware/firmware_a1_nt_a.o"
	@echo "... src/firmware/firmware_a1_nt_a.i"
	@echo "... src/firmware/firmware_a1_nt_a.s"
	@echo "... src/firmware/firmware_database.o"
	@echo "... src/firmware/firmware_database.i"
	@echo "... src/firmware/firmware_database.s"
	@echo "... src/firmware/firmware_t20.o"
	@echo "... src/firmware/firmware_t20.i"
	@echo "... src/firmware/firmware_t20.s"
	@echo "... src/firmware/firmware_t21.o"
	@echo "... src/firmware/firmware_t21.i"
	@echo "... src/firmware/firmware_t21.s"
	@echo "... src/firmware/firmware_t23.o"
	@echo "... src/firmware/firmware_t23.i"
	@echo "... src/firmware/firmware_t23.s"
	@echo "... src/firmware/firmware_t30.o"
	@echo "... src/firmware/firmware_t30.i"
	@echo "... src/firmware/firmware_t30.s"
	@echo "... src/firmware/firmware_t30a.o"
	@echo "... src/firmware/firmware_t30a.i"
	@echo "... src/firmware/firmware_t30a.s"
	@echo "... src/firmware/firmware_t30nl.o"
	@echo "... src/firmware/firmware_t30nl.i"
	@echo "... src/firmware/firmware_t30nl.s"
	@echo "... src/firmware/firmware_t30x.o"
	@echo "... src/firmware/firmware_t30x.i"
	@echo "... src/firmware/firmware_t30x.s"
	@echo "... src/firmware/firmware_t31.o"
	@echo "... src/firmware/firmware_t31.i"
	@echo "... src/firmware/firmware_t31.s"
	@echo "... src/firmware/firmware_t31a.o"
	@echo "... src/firmware/firmware_t31a.i"
	@echo "... src/firmware/firmware_t31a.s"
	@echo "... src/firmware/firmware_t31nl.o"
	@echo "... src/firmware/firmware_t31nl.i"
	@echo "... src/firmware/firmware_t31nl.s"
	@echo "... src/firmware/firmware_t31x.o"
	@echo "... src/firmware/firmware_t31x.i"
	@echo "... src/firmware/firmware_t31x.s"
	@echo "... src/firmware/firmware_t40.o"
	@echo "... src/firmware/firmware_t40.i"
	@echo "... src/firmware/firmware_t40.s"
	@echo "... src/firmware/firmware_t41.o"
	@echo "... src/firmware/firmware_t41.i"
	@echo "... src/firmware/firmware_t41.s"
	@echo "... src/firmware/flash_descriptor.o"
	@echo "... src/firmware/flash_descriptor.i"
	@echo "... src/firmware/flash_descriptor.s"
	@echo "... src/firmware/handshake.o"
	@echo "... src/firmware/handshake.i"
	@echo "... src/firmware/handshake.s"
	@echo "... src/firmware/loader.o"
	@echo "... src/firmware/loader.i"
	@echo "... src/firmware/loader.s"
	@echo "... src/firmware/reader.o"
	@echo "... src/firmware/reader.i"
	@echo "... src/firmware/reader.s"
	@echo "... src/firmware/writer.o"
	@echo "... src/firmware/writer.i"
	@echo "... src/firmware/writer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test_binary_builder.o"
	@echo "... src/test_binary_builder.i"
	@echo "... src/test_binary_builder.s"
	@echo "... src/test_config_database.o"
	@echo "... src/test_config_database.i"
	@echo "... src/test_config_database.s"
	@echo "... src/test_ddr_generator.o"
	@echo "... src/test_ddr_generator.i"
	@echo "... src/test_ddr_generator.s"
	@echo "... src/test_ddr_integration.o"
	@echo "... src/test_ddr_integration.i"
	@echo "... src/test_ddr_integration.s"
	@echo "... src/test_ddr_mapping_analysis.o"
	@echo "... src/test_ddr_mapping_analysis.i"
	@echo "... src/test_ddr_mapping_analysis.s"
	@echo "... src/test_ddr_multiplechip.o"
	@echo "... src/test_ddr_multiplechip.i"
	@echo "... src/test_ddr_multiplechip.s"
	@echo "... src/test_ddr_reference_analysis.o"
	@echo "... src/test_ddr_reference_analysis.i"
	@echo "... src/test_ddr_reference_analysis.s"
	@echo "... src/test_ddrc_analysis.o"
	@echo "... src/test_ddrc_analysis.i"
	@echo "... src/test_ddrc_analysis.s"
	@echo "... src/test_firmware_database.o"
	@echo "... src/test_firmware_database.i"
	@echo "... src/test_firmware_database.s"
	@echo "... src/test_txx_mapping_analysis.o"
	@echo "... src/test_txx_mapping_analysis.i"
	@echo "... src/test_txx_mapping_analysis.s"
	@echo "... src/usb/device.o"
	@echo "... src/usb/device.i"
	@echo "... src/usb/device.s"
	@echo "... src/usb/manager.o"
	@echo "... src/usb/manager.i"
	@echo "... src/usb/manager.s"
	@echo "... src/usb/protocol.o"
	@echo "... src/usb/protocol.i"
	@echo "... src/usb/protocol.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

